# Generated by Django 5.2 on 2025-04-30 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='Use um nome curto, diferente da razão social, mas que seja único. Se o seu cadastro possuir mais de uma filial, tenha nomes diferentes para cada uma.', max_length=32, unique=True, verbose_name='Empresa')),
                ('name', models.CharField(max_length=64, verbose_name='Razão social')),
                ('cnpj', models.CharField(blank=True, max_length=32, unique=True, verbose_name='CNPJ')),
                ('email', models.CharField(blank=True, max_length=320, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Telefone')),
                ('website', models.CharField(blank=True, max_length=64, verbose_name='Website')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address_manager.address')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['short_name'],
                'indexes': [models.Index(fields=['cnpj'], name='company_man_cnpj_bdaf1f_idx'), models.Index(fields=['short_name'], name='company_man_short_n_94f691_idx')],
            },
        ),
    ]
