# Generated by Django 5.2 on 2025-05-04 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_manager', '0001_initial'),
        ('company_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address_manager.address', verbose_name='Endereço'),
        ),
    ]
