# Generated by Django 5.2 on 2025-05-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_manager', '0002_alter_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=32, unique=True, verbose_name='CNPJ'),
        ),
    ]
