# Generated by Django 5.2 on 2025-05-12 00:30

import company_manager.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_manager', '0003_alter_company_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=32, unique=True, validators=[company_manager.validators.validate_cnpj], verbose_name='CNPJ'),
        ),
    ]
