# Generated by Django 5.2 on 2025-05-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Use um nome que descreva bem um item/produto.', max_length=64, unique=True, verbose_name='Nome')),
                ('brand', models.CharField(blank=True, max_length=64, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=128, verbose_name='Modelo')),
                ('color', models.CharField(blank=True, max_length=16, verbose_name='Cor')),
                ('author', models.CharField(blank=True, max_length=128, verbose_name='Autor(es)')),
                ('sku', models.CharField(blank=True, max_length=16, verbose_name='SKU')),
                ('upc', models.CharField(blank=True, max_length=16, verbose_name='upc')),
                ('barcode', models.CharField(blank=True, max_length=16, verbose_name='Código de barras')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso')),
                ('weight_unit', models.CharField(blank=True, choices=[('mg', 'miligramas'), ('kg', 'quilogramas'), ('g', 'gramas'), ('lb', 'libras'), ('oz', 'onças')], default='kg', max_length=2, verbose_name='Unidade de peso')),
                ('dimension_x', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Comprimento')),
                ('dimension_y', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='largura')),
                ('dimension_z', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Profundidade')),
                ('dimension_unit', models.CharField(blank=True, choices=[('mm', 'milímetros'), ('cm', 'centímetros'), ('m', 'metros'), ('in', 'polegadas'), ('ft', 'pés')], default='cm', max_length=2, verbose_name='Unidade de medida')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='category_ma_name_8e0ec7_idx'), models.Index(fields=['sku'], name='category_ma_sku_4488a3_idx'), models.Index(fields=['upc'], name='category_ma_upc_0d3b0f_idx'), models.Index(fields=['barcode'], name='category_ma_barcode_5af17b_idx')],
            },
        ),
    ]
