# Generated by Django 5.2 on 2025-05-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='upc',
            field=models.CharField(blank=True, max_length=16, verbose_name='UPC'),
        ),
    ]
