# Generated by Django 5.2 on 2025-05-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_manager', '0003_category_is_fungible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='author',
            field=models.CharField(blank=True, max_length=256, verbose_name='Autor(es)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, max_length=32, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='category',
            name='dimension_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Comprimento'),
        ),
        migrations.AlterField(
            model_name='category',
            name='dimension_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='largura'),
        ),
        migrations.AlterField(
            model_name='category',
            name='dimension_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Profundidade'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_fungible',
            field=models.BooleanField(default=False, help_text='Marque se os itens criados a partir dessa categoria não necessitam de controle individual como etiqueta de patrimônio ou número de série. Exemplo: Caneta Bic Azul, Resma de Papel A4 - 500 folhas, etc.', verbose_name='Fungível'),
        ),
        migrations.AlterField(
            model_name='category',
            name='model',
            field=models.CharField(blank=True, max_length=256, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Use um nome que descreva bem um item/produto.', max_length=256, unique=True, verbose_name='Nome'),
        ),
    ]
