# Generated by Django 5.2 on 2025-05-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_manager', '0004_alter_category_author_alter_category_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='barcode',
            field=models.CharField(blank=True, max_length=16, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='category',
            name='dimension_unit',
            field=models.CharField(blank=True, choices=[('mm', 'milímetros'), ('cm', 'centímetros'), ('m', 'metros'), ('in', 'polegadas'), ('ft', 'pés')], default='cm', max_length=2, verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='category',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('mg', 'miligramas'), ('kg', 'quilogramas'), ('g', 'gramas'), ('lb', 'libras'), ('oz', 'onças')], default='kg', max_length=2, verbose_name='Unidade de Peso'),
        ),
    ]
