# Generated by Django 5.2 on 2025-05-05 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address_manager', '0002_alter_address_neighborhood'),
        ('company_manager', '0003_alter_company_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=32, unique=True, verbose_name='CPF')),
                ('full_name', models.CharField(max_length=64, verbose_name='Nome completo')),
                ('email', models.CharField(blank=True, max_length=320, verbose_name='Email')),
                ('rg', models.CharField(blank=True, max_length=32, verbose_name='RG')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Telefone')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('comment', models.TextField(blank=True, verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address_manager.address', verbose_name='Endereço completo')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='company_manager.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['cpf'], name='person_mana_cpf_701d2c_idx'), models.Index(fields=['full_name'], name='person_mana_full_na_e9021c_idx')],
            },
        ),
    ]
