# Generated by Django 5.2 on 2025-05-12 00:30

import person_manager.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(max_length=32, unique=True, validators=[person_manager.validators.validate_cpf], verbose_name='CPF'),
        ),
    ]
