# Generated by Django 5.2 on 2025-04-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=16, verbose_name='CEP')),
                ('street', models.CharField(max_length=64, verbose_name='Logradouro')),
                ('number', models.CharField(blank=True, max_length=8, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=32, verbose_name='Complemento')),
                ('neighborhood', models.CharField(max_length=32, verbose_name='Bairro')),
                ('city', models.CharField(max_length=64, verbose_name='Cidade')),
                ('state', models.CharField(max_length=64, verbose_name='Estado')),
                ('country', models.CharField(default='Brasil', max_length=64, verbose_name='País')),
                ('reference', models.TextField(blank=True, verbose_name='Referência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['zip_code', 'street', 'number'],
                'indexes': [models.Index(fields=['zip_code'], name='address_man_zip_cod_d62aa4_idx')],
            },
        ),
    ]
