# Generated by Django 5.2 on 2025-05-07 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_manager', '0003_alter_company_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Use um nome curto, único, que descreva bem o local.', max_length=64, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='company_manager.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Armazém',
                'verbose_name_plural': 'Armazéns',
                'ordering': ['name', 'description'],
                'indexes': [models.Index(fields=['name'], name='warehouse_m_name_43312b_idx'), models.Index(fields=['company'], name='warehouse_m_company_7259c9_idx')],
            },
        ),
    ]
