# Generated by Django 5.2 on 2025-05-07 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_manager', '0003_alter_company_cnpj'),
        ('item_manager', '0002_alter_item_is_new'),
        ('person_manager', '0001_initial'),
        ('warehouse_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InflowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('purchase', 'Compra'), ('donation', 'Doação'), ('borrow', 'Empréstimo'), ('return', 'Retorno'), ('transfer', 'Transferência')], default='purchase', max_length=32, verbose_name='Tipo de entrada')),
                ('invoice', models.CharField(blank=True, help_text='Procure usar exatamente o mesmo valor para todos os itens que estão na mesma nota fiscal ou recibo.', max_length=32, null=True, verbose_name='Nota fiscal ou recibo')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('company_counterpart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inflows', to='company_manager.company', verbose_name='Contraparte (empresa)')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inflows', to='item_manager.item', verbose_name='Item')),
                ('person_counterpart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inflows', to='person_manager.person', verbose_name='Contraparte (pessoa)')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inflows', to='warehouse_manager.warehouse', verbose_name='Armazém')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['created_at', 'item'],
                'indexes': [models.Index(fields=['warehouse'], name='warehouse_m_warehou_8ea681_idx'), models.Index(fields=['item'], name='warehouse_m_item_id_fb06fc_idx'), models.Index(fields=['company_counterpart'], name='warehouse_m_company_054319_idx'), models.Index(fields=['person_counterpart'], name='warehouse_m_person__c1373e_idx')],
            },
        ),
        migrations.CreateModel(
            name='OutflowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sale', 'Venda'), ('donation', 'Doação'), ('lent', 'Empréstimo'), ('return', 'Devolução'), ('transfer', 'Transferência'), ('waste', 'Descarte')], default='sale', max_length=32, verbose_name='Tipo de saída')),
                ('invoice', models.CharField(blank=True, help_text='Procure usar exatamente o mesmo valor para todos os itens que estão na mesma nota fiscal ou recibo.', max_length=32, null=True, verbose_name='Nota fiscal ou recibo')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('company_counterpart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outflows', to='company_manager.company', verbose_name='Contraparte (empresa)')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outflows', to='item_manager.item', verbose_name='Item')),
                ('person_counterpart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outflows', to='person_manager.person', verbose_name='Contraparte (pessoa)')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outflows', to='warehouse_manager.warehouse', verbose_name='Armazém')),
            ],
            options={
                'verbose_name': 'Saída',
                'verbose_name_plural': 'Saídas',
                'ordering': ['created_at', 'item'],
                'indexes': [models.Index(fields=['warehouse'], name='warehouse_m_warehou_359d62_idx'), models.Index(fields=['item'], name='warehouse_m_item_id_5dc62b_idx'), models.Index(fields=['company_counterpart'], name='warehouse_m_company_4175d2_idx'), models.Index(fields=['person_counterpart'], name='warehouse_m_person__f5ee4c_idx')],
            },
        ),
    ]
