# Generated by Django 5.2 on 2025-05-06 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_tag', models.CharField(blank=True, max_length=32, verbose_name='Etiqueta de Patrimônio')),
                ('serial_number', models.CharField(blank=True, max_length=32, verbose_name='Número de Série')),
                ('is_new', models.BooleanField(blank=True, default=True, verbose_name='Novo?')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='category_manager.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['category', 'corporate_tag'],
                'indexes': [models.Index(fields=['corporate_tag'], name='item_manage_corpora_37d48d_idx'), models.Index(fields=['serial_number'], name='item_manage_serial__e2c33a_idx'), models.Index(fields=['category'], name='item_manage_categor_b0b568_idx')],
            },
        ),
    ]
