# Generated by Django 5.2 on 2025-05-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_new',
            field=models.BooleanField(blank=True, default=True, verbose_name='novo (marque se o item nunca foi usado anteriormente)'),
        ),
    ]
