# Generated by Django 5.2 on 2025-05-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_manager', '0002_alter_item_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='corporate_tag',
            field=models.CharField(blank=True, help_text='Número que identifica exclusivamente um item dentro de uma empresa ou instituição. Exemplo: 123456, 1234-5678, etc.', max_length=32, verbose_name='Etiqueta de Patrimônio'),
        ),
        migrations.AlterField(
            model_name='item',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Número que identifica exclusivamente um item. Por exemplo: o IMEI de um celular, o número de série de um computador, etc.', max_length=32, verbose_name='Número de Série'),
        ),
    ]
