# Generated by Django 5.2 on 2025-05-08 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_manager', '0003_alter_company_cnpj'),
        ('item_manager', '0002_alter_item_is_new'),
        ('person_manager', '0001_initial'),
        ('warehouse_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('purchase', 'Compra'), ('sale', 'Venda'), ('donation', 'Doação'), ('borrow', 'Empréstimo'), ('lent', 'Empréstimo'), ('return', 'Retorno'), ('transfer', 'Transferência'), ('waste', 'Descarte')], default='sale', max_length=32, verbose_name='Tipo')),
                ('invoice', models.CharField(blank=True, help_text='Procure usar exatamente o mesmo valor para todos os itens que estão na mesma nota fiscal ou recibo.', max_length=32, null=True, verbose_name='Nota fiscal ou recibo')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço')),
                ('beginning_date', models.DateField(blank=True, null=True, verbose_name='Data de início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de término')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('company_counterpart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='company_manager.company', verbose_name='Contraparte (empresa)')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outflows', to='item_manager.item', verbose_name='Item')),
                ('person_counterpart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='person_manager.person', verbose_name='Contraparte (pessoa)')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='warehouse_manager.warehouse', verbose_name='Armazém')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['created_at', 'item'],
                'indexes': [models.Index(fields=['warehouse'], name='transaction_warehou_22f290_idx'), models.Index(fields=['type'], name='transaction_type_78f291_idx'), models.Index(fields=['item'], name='transaction_item_id_2cdb72_idx'), models.Index(fields=['invoice'], name='transaction_invoice_ba413d_idx'), models.Index(fields=['company_counterpart'], name='transaction_company_cdc381_idx'), models.Index(fields=['person_counterpart'], name='transaction_person__d76454_idx')],
            },
        ),
    ]
