# Generated by Django 5.2 on 2025-05-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('compra', 'Compra'), ('venda', 'Venda'), ('doação', 'Doação'), ('empréstimo', 'Empréstimo'), ('retorno', 'Retorno'), ('transferência', 'Transferência'), ('descarte', 'Descarte')], default='sale', max_length=32, verbose_name='Tipo'),
        ),
    ]
