# Generated by Django 5.2 on 2025-05-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_manager', '0002_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_inflow',
            field=models.BooleanField(default=True, verbose_name='Operação de entrada'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('compra', 'Compra'), ('venda', 'Venda'), ('doação', 'Doação'), ('empréstimo', 'Empréstimo'), ('retorno', 'Retorno'), ('transferência', 'Transferência'), ('descarte', 'Descarte')], default='compra', max_length=32, verbose_name='Tipo'),
        ),
    ]
