# Generated by Django 5.2 on 2025-05-12 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_manager', '0002_alter_person_cpf'),
        ('transaction_manager', '0003_transaction_is_inflow_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_actor', to='person_manager.person', verbose_name='Pessoa que executou a transação'),
        ),
    ]
