# Generated by Django 5.2 on 2025-05-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_manager', '0004_transaction_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='beginning_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Término'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='invoice',
            field=models.CharField(blank=True, help_text='Procure usar exatamente o mesmo valor para todos os itens que estão na mesma nota fiscal ou recibo.', max_length=32, null=True, verbose_name='Nota Fiscal ou Recibo'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_inflow',
            field=models.BooleanField(default=True, verbose_name='Operação de Entrada'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('compra', 'Compra'), ('venda', 'Venda'), ('doação (entrada)', 'Doação (Entrada)'), ('doação (saída)', 'Doação (Saída)'), ('empréstimo (entrada)', 'Empréstimo (Entrada)'), ('empréstimo (saída)', 'Empréstimo (Saída)'), ('retorno (entrada)', 'Retorno (Entrada)'), ('retorno (saída)', 'Retorno (Saída)'), ('transferência (entrada)', 'Transferência (Entrada)'), ('transferência (saída)', 'Transferência (Saída)'), ('descarte', 'Descarte')], default='compra', max_length=32, verbose_name='Tipo'),
        ),
    ]
